// <auto-generated />
namespace Bids.WebUI.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddItemUserIDColummn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddItemUserIDColummn));
        
        string IMigrationMetadata.Id
        {
            get { return "201402230913183_AddItemUserIDColummn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
