// <auto-generated />
namespace Bids.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ItemTitleAndDateRequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ItemTitleAndDateRequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201402201605399_ItemTitleAndDateRequired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
